// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var UWebSocketsJs = require("uWebSockets.js");

UWebSocketsJs.App().get("/*", (function (res, req) {
          res.writeStatus("200 OK").end("usukawa v0.1.0");
          console.log(req.getUrl());
          
        })).listen(5555, (function (_listenSocket) {
        console.log("listen!");
        
      }));

/*  Not a pure module */
